//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelterManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FindingReportRecord
    {
        public int HomelessAnimalId { get; set; }
        public int FindingReportId { get; set; }
        public int AnimalShelterId { get; set; }
        public System.DateTime ProtectionStartDate { get; set; }
    
        public virtual AnimalShelter AnimalShelter { get; set; }
        public virtual FindingReport FindingReport { get; set; }
        public virtual HomelessAnimal HomelessAnimal { get; set; }
    }
}
