//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalShelterManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoundAnimalRecord
    {
        public int LossReportId { get; set; }
        public int HomelessAnimalId { get; set; }
        public string Detail { get; set; }
    
        public virtual HomelessAnimal HomelessAnimal { get; set; }
    }
}
